# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 12:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=1000, null=True)),
                ('off', models.IntegerField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, editable=False, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyOrdersDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DailyOrdersLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datentime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DS', 'Dispatched'), ('DL', 'Delivered'), ('CN', 'Cancelled')], default='DS', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DailyProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.CharField(blank=True, max_length=300, null=True)),
                ('cat2', models.CharField(blank=True, max_length=300, null=True)),
                ('cat3', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
                ('sp', models.CharField(blank=True, max_length=300, null=True)),
                ('mrp', models.CharField(blank=True, max_length=300, null=True)),
                ('quantity', models.CharField(blank=True, max_length=300, null=True)),
                ('PercentOff', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('image', models.IntegerField(blank=True, editable=False, null=True)),
                ('enable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DailySubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, editable=False, null=True)),
                ('total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('datentime', models.DateTimeField(auto_now=True)),
                ('customdate', models.CharField(blank=True, max_length=300, null=True)),
                ('datetype', models.CharField(choices=[('DF', 'Default'), ('CT', 'Custom')], default='DF', max_length=2)),
                ('days', models.CharField(blank=True, max_length=10, null=True)),
                ('paytype', models.CharField(choices=[('ON', 'Online Payment'), ('CS', 'Cash On Delivery'), ('X', 'Not Yet')], default='X', max_length=2)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('network', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBoyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('lat', models.FloatField(blank=True, default='12.8351384', null=True)),
                ('lon', models.FloatField(blank=True, default='77.656235', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Delivery Man')),
            ],
        ),
        migrations.CreateModel(
            name='EbsPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsecode', models.CharField(max_length=30)),
                ('transactionid', models.CharField(max_length=30)),
                ('refno', models.CharField(max_length=30)),
                ('hash', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratetype', models.CharField(max_length=1)),
                ('comments', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.CharField(blank=True, max_length=300, null=True)),
                ('cat2', models.CharField(blank=True, max_length=300, null=True)),
                ('cat3', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('brand', models.CharField(blank=True, max_length=300, null=True)),
                ('sp', models.CharField(blank=True, max_length=300, null=True)),
                ('mrp', models.CharField(blank=True, max_length=300, null=True)),
                ('quantity', models.CharField(blank=True, max_length=300, null=True)),
                ('PercentOff', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('enable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productidarray', models.CharField(max_length=300)),
                ('quantityidarray', models.CharField(max_length=300)),
                ('total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('datentime', models.DateTimeField(auto_now=True)),
                ('paytype', models.CharField(choices=[('ON', 'Online Payment'), ('CS', 'Cash On Delivery'), ('X', 'Not Yet')], default='X', max_length=2)),
                ('type', models.CharField(choices=[('FO', 'Food type'), ('GR', 'Groceries')], default='GR', max_length=2)),
                ('status', models.CharField(choices=[('AC', 'Accepted'), ('DS', 'Dispatched'), ('DL', 'Delivered'), ('CN', 'Cancelled'), ('PL', 'Placed'), ('IN', 'Initiated'), ('PF', 'Payment Failed')], default='PL', max_length=2)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('network', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restapi.Orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Delivery Boy')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.CharField(blank=True, max_length=300, null=True)),
                ('cat2', models.CharField(blank=True, max_length=300, null=True)),
                ('cat3', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('brand', models.CharField(blank=True, max_length=300, null=True)),
                ('sp', models.CharField(blank=True, max_length=300, null=True)),
                ('mrp', models.CharField(blank=True, max_length=300, null=True)),
                ('PercentOff', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('quantity', models.CharField(blank=True, max_length=300, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=restapi.models.sample_upload)),
                ('image', models.IntegerField(blank=True, editable=False, null=True)),
                ('enable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('house', models.CharField(blank=True, max_length=100)),
                ('area1', models.CharField(blank=True, max_length=100)),
                ('area2', models.CharField(blank=True, max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('otp', models.CharField(max_length=4, null=True)),
                ('otpstatus', models.BooleanField()),
                ('model', models.CharField(max_length=100, null=True)),
                ('version', models.CharField(max_length=100, null=True)),
                ('uuid', models.CharField(max_length=100, null=True)),
                ('man', models.CharField(max_length=100, null=True)),
                ('wallet', models.IntegerField(blank=True, editable=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.UserAddress'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Orders'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ebspayments',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restapi.Orders'),
        ),
        migrations.AddField(
            model_name='ebspayments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailysubscriptions',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.UserAddress'),
        ),
        migrations.AddField(
            model_name='dailysubscriptions',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.DailyProducts'),
        ),
        migrations.AddField(
            model_name='dailysubscriptions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyorderslog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.DailySubscriptions'),
        ),
        migrations.AddField(
            model_name='dailyorderslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyordersdelivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restapi.DailyOrdersLog'),
        ),
        migrations.AddField(
            model_name='dailyordersdelivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Delivery Boy'),
        ),
    ]
